baseurl = "https://segflow.github.io/"
relativeURLs = true
languageCode = "en-us"
title = "Segflow"
disqusShortname = "segflow-io"
paginate = 5
themesdir = "themes/"
theme = "hugo-geo"


[params]
	# Render the rotating globe in the sidebar
	showglobe = true

	# Include favicon
	favicon = "favicon.ico"
 	
	# Google Analytics
	analytics = "UA-111743535-1"

	# Email (optional)
	email = "asselmeher@gmail.com"
	
	# Header Title for the main page
	header = "Let's pwn!"
	
	# Sidebar profile picture
	profilepic = "img/hacker_emblem.png"
	
	# Title/subtitle for the sidebar
	title = "Segflow"
	subtitle = "Assel Meher"
	
	# Social buttons for sidebar
	# Each of these are optional
	[[params.socialbuttons]]
	faicon = "github"
	url = "https://github.com/segflow"
	[[params.socialbuttons]]
	faicon = "linkedin"
	url = "https://www.linkedin.com/in/meher-assel-0122798a"


	# Nav links below the profile picture
	[[params.navlinks]]
	name = "Home"
	url = "/"
	
	[[params.navlinks]]
	name = "Posts"
	url = "post/"
	